apiVersion: v1
kind: Service
metadata:
  name: usersmicroservice
  labels:
    name: usersmicroservice
spec:
  ports:
    - name: http
      targetPort: 3002
      port: 3002
      protocol: TCP
  selector:
    app: madclones
    task: usersmicroservice
    name: usersmicroservice