apiVersion: v1
kind: Service
metadata:
  name: trellomicroservice
  labels:
    name: trellomicroservice
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    name: trellomicroservice