apiVersion: v1
kind: Service
metadata:
  name: usersmicroservice
  labels:
    name: usersmicroservice
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    name: usersmicroservice