apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trellodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trellodb
    spec:
      containers:
        - image: mongo
          name: trellodb
          imagePullPolicy: Always
          ports:
            - name: trellodb
              containerPort: 27017
          volumeMounts:
            - name: trellodbvol
              mountPath: /data/db
      volumes:
        - name: trellodbvol