apiVersion: v1
kind: Service
metadata:
  name: trellomicroservice
  labels:
    name: trellomicroservice
spec:
  ports:
    - name: http
      targetPort: 3001
      port: 3001
      protocol: TCP
  selector:
    app: madclones
    task: trellomicroservice
    name: trellomicroservice